"""initial_schema

Revision ID: cf45ec2c79be
Revises: 
Create Date: 2026-03-21 12:26:34.001625
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf45ec2c79be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_slug'), 'categoria', ['slug'], unique=True)
    op.create_table('checkout_iniciado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrito_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('pais_origen', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_marca_slug'), 'marca', ['slug'], unique=True)
    op.create_table('nota_olfativa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('familia', sa.Enum('CITRICO', 'AMADERADO', 'FLORAL', 'ORIENTAL', 'DULCE', 'FRESCO', 'ESPECIADO', 'ACUATICO', name='familia_olfativa_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('promocion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('INDIVIDUAL', 'GLOBAL', 'PAQUETE', name='tipo_promocion_enum'), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descuento_fijo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zona_envio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('zona_envio_id', sa.UUID(), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO', name='estado_pedido_enum'), nullable=False),
    sa.Column('metodo_pago', sa.Enum('TRANSFERENCIA', 'PAGO_MOVIL', 'EFECTIVO', 'ZELLE', name='metodo_pago_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zona_envio_id'], ['zona_envio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_created_at'), 'pedido', ['created_at'], unique=False)
    op.create_index(op.f('ix_pedido_estado'), 'pedido', ['estado'], unique=False)
    op.create_table('perfume',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('marca_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('genero', sa.Enum('HOMBRE', 'MUJER', 'UNISEX', name='genero_enum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('es_arabe', sa.Boolean(), nullable=False),
    sa.Column('es_nuevo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_categoria_id'), 'perfume', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_perfume_es_arabe'), 'perfume', ['es_arabe'], unique=False)
    op.create_index(op.f('ix_perfume_es_nuevo'), 'perfume', ['es_nuevo'], unique=False)
    op.create_index(op.f('ix_perfume_genero'), 'perfume', ['genero'], unique=False)
    op.create_index(op.f('ix_perfume_marca_id'), 'perfume', ['marca_id'], unique=False)
    op.create_index(op.f('ix_perfume_slug'), 'perfume', ['slug'], unique=True)
    op.create_table('imagen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('perfume_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagen_perfume_id'), 'imagen', ['perfume_id'], unique=False)
    op.create_table('perfume_nota',
    sa.Column('perfume_id', sa.UUID(), nullable=False),
    sa.Column('nota_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('SALIDA', 'CORAZON', 'FONDO', name='tipo_nota_enum'), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota_olfativa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfume_id', 'nota_id', 'tipo')
    )
    op.create_table('presentacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('perfume_id', sa.UUID(), nullable=False),
    sa.Column('tamano_ml', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentacion_perfume_id'), 'presentacion', ['perfume_id'], unique=False)
    op.create_table('pedido_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('presentacion_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentacion_id'], ['presentacion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_item_pedido_id'), 'pedido_item', ['pedido_id'], unique=False)
    op.create_table('promocion_producto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promocion_id', sa.UUID(), nullable=False),
    sa.Column('perfume_id', sa.UUID(), nullable=False),
    sa.Column('presentacion_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentacion_id'], ['presentacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocion_producto_promocion_id'), 'promocion_producto', ['promocion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promocion_producto_promocion_id'), table_name='promocion_producto')
    op.drop_table('promocion_producto')
    op.drop_index(op.f('ix_pedido_item_pedido_id'), table_name='pedido_item')
    op.drop_table('pedido_item')
    op.drop_index(op.f('ix_presentacion_perfume_id'), table_name='presentacion')
    op.drop_table('presentacion')
    op.drop_table('perfume_nota')
    op.drop_index(op.f('ix_imagen_perfume_id'), table_name='imagen')
    op.drop_table('imagen')
    op.drop_index(op.f('ix_perfume_slug'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_marca_id'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_genero'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_es_nuevo'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_es_arabe'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_categoria_id'), table_name='perfume')
    op.drop_table('perfume')
    op.drop_index(op.f('ix_pedido_estado'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_created_at'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_table('zona_envio')
    op.drop_table('promocion')
    op.drop_table('nota_olfativa')
    op.drop_index(op.f('ix_marca_slug'), table_name='marca')
    op.drop_table('marca')
    op.drop_table('checkout_iniciado')
    op.drop_index(op.f('ix_categoria_slug'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
