"""add_activo_to_admin_user

Revision ID: d30882d47fc0
Revises: 7d1b3e8f2c05
Create Date: 2026-06-06 14:54:32.386498
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd30882d47fc0'
down_revision: Union[str, None] = '7d1b3e8f2c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('admin_user')]
    if 'activo' not in columns:
        op.add_column(
            'admin_user',
            sa.Column('activo', sa.Boolean(), nullable=False, server_default='true')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('admin_user')]
    if 'activo' in columns:
        op.drop_column('admin_user', 'activo')
    # ### end Alembic commands ###
